// Package context implements the Super Context generator for the Hyperax Agent OS.
//
// Super Context watches workspaces and auto-generates agent context files
// (CLAUDE.md, .gemini, etc.) by pulling data from project plans, active tasks,
// coding standards, documentation, and pipeline definitions. The generated
// files carry a CASAT_MANAGED header so agents know not to edit them manually.
package context

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/hyperax/hyperax/internal/nervous"
	"github.com/hyperax/hyperax/internal/repo"
	"github.com/hyperax/hyperax/internal/storage"
)

// managedHeader is prepended to every generated context file so agents and
// humans know the file is machine-managed and should not be edited by hand.
const managedHeader = "<!-- CASAT_MANAGED: Do not edit manually. Regenerated by CASAT SuperContext System. -->"

// SuperContextGenerator produces structured agent context files by querying
// the Store for workspace metadata, project plans, tasks, pipelines, and docs.
type SuperContextGenerator struct {
	store  *storage.Store
	bus    *nervous.EventBus
	logger *slog.Logger
}

// NewSuperContextGenerator creates a SuperContextGenerator.
//
// Parameters:
//   - store: the composed Store facade providing access to all repos.
//   - bus: the EventBus for publishing generation events (may be nil).
//   - logger: structured logger for operational diagnostics.
func NewSuperContextGenerator(store *storage.Store, bus *nervous.EventBus, logger *slog.Logger) *SuperContextGenerator {
	if logger == nil {
		logger = slog.Default()
	}
	return &SuperContextGenerator{
		store:  store,
		bus:    bus,
		logger: logger,
	}
}

// Generate produces the full context content for a workspace as a structured
// markdown document. It queries the store for projects, tasks, standards,
// docs, and pipelines, assembling them into a format useful for AI agents.
//
// Parameters:
//   - ctx: cancellation context.
//   - workspaceID: the workspace name/ID to generate context for.
//   - rootPath: the filesystem root path of the workspace.
//
// Returns the generated markdown string, or an error if the workspace cannot
// be resolved or a critical query fails.
func (g *SuperContextGenerator) Generate(ctx context.Context, workspaceID string, rootPath string) (string, error) {
	g.logger.Info("generating super context", "workspace", workspaceID, "root", rootPath)

	var sb strings.Builder

	// Header
	sb.WriteString(managedHeader)
	sb.WriteString("\n\n")

	// Project Overview
	g.writeProjectOverview(&sb, workspaceID, rootPath)

	// Active Project Plans
	if err := g.writeProjectPlans(ctx, &sb, workspaceID); err != nil {
		g.logger.Warn("failed to write project plans section", "error", err)
	}

	// Active Tasks (in-progress)
	if err := g.writeActiveTasks(ctx, &sb, workspaceID); err != nil {
		g.logger.Warn("failed to write active tasks section", "error", err)
	}

	// CASAT Operational Mandates
	g.writeOperationalMandates(&sb)

	// Tool-First Workflow
	g.writeToolWorkflow(&sb)

	// Coding Standards
	g.writeCodingStandards(&sb, rootPath)

	// Recent Documentation
	g.writeRecentDocs(&sb, rootPath)

	// Pipeline Definitions
	if err := g.writePipelines(ctx, &sb, workspaceID); err != nil {
		g.logger.Warn("failed to write pipelines section", "error", err)
	}

	return sb.String(), nil
}

// WriteContextFile generates and writes the context to a CLAUDE.md file in
// the workspace root. If the file already exists and carries the CASAT_MANAGED
// header, it is overwritten. Files without the header are left untouched to
// avoid clobbering user-authored content.
//
// Parameters:
//   - ctx: cancellation context.
//   - workspaceID: the workspace name/ID.
//   - rootPath: the filesystem root path of the workspace.
//
// Returns an error if generation or file I/O fails.
func (g *SuperContextGenerator) WriteContextFile(ctx context.Context, workspaceID string, rootPath string) error {
	content, err := g.Generate(ctx, workspaceID, rootPath)
	if err != nil {
		return fmt.Errorf("context.SuperContextGenerator.WriteContextFile: generate: %w", err)
	}

	targetPath := filepath.Join(rootPath, string(ContextClaude))

	// Safety check: if the file exists but is NOT managed by us, refuse to
	// overwrite. This prevents destroying user-authored CLAUDE.md files.
	if existing, readErr := os.ReadFile(targetPath); readErr == nil {
		if !strings.HasPrefix(string(existing), "<!-- CASAT_MANAGED") {
			return fmt.Errorf("context.SuperContextGenerator.WriteContextFile: refusing to overwrite %s: file exists but is not CASAT-managed", targetPath)
		}
	}

	if err := os.WriteFile(targetPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("context.SuperContextGenerator.WriteContextFile: write file: %w", err)
	}

	g.logger.Info("wrote super context file", "path", targetPath, "workspace", workspaceID)
	return nil
}

// ---------------------------------------------------------------------------
// Section writers
// ---------------------------------------------------------------------------

// writeProjectOverview writes the top-level project overview section with
// workspace name and root path.
func (g *SuperContextGenerator) writeProjectOverview(sb *strings.Builder, workspaceID, rootPath string) {
	sb.WriteString("# ")
	sb.WriteString(workspaceID)
	sb.WriteString(" — CASAT Managed Context\n\n")
	sb.WriteString("## Project Overview\n\n")
	sb.WriteString("**Workspace:** ")
	sb.WriteString(workspaceID)
	sb.WriteString("\n")
	sb.WriteString("**Root:** `")
	sb.WriteString(rootPath)
	sb.WriteString("`\n\n")
}

// writeProjectPlans queries the Projects repo for all plans in the workspace
// and writes them as a bulleted list with status and priority.
func (g *SuperContextGenerator) writeProjectPlans(ctx context.Context, sb *strings.Builder, workspaceID string) error {
	if g.store.Projects == nil {
		sb.WriteString("## Active Project Plans\n\n")
		sb.WriteString("No project management available.\n\n")
		return nil
	}

	plans, err := g.store.Projects.ListProjectPlans(ctx, workspaceID)
	if err != nil {
		sb.WriteString("## Active Project Plans\n\n")
		sb.WriteString("Unable to retrieve project plans.\n\n")
		return fmt.Errorf("context.SuperContextGenerator.writeProjectPlans: %w", err)
	}

	sb.WriteString("## Active Project Plans\n\n")

	if len(plans) == 0 {
		sb.WriteString("No project plans configured.\n\n")
		return nil
	}

	sb.WriteString("Use `get_project_details` (project_id) or `list_tasks` to view and manage:\n\n")
	for _, p := range plans {
		fmt.Fprintf(sb, "- **%s** (`%s`) — %s / %s\n", p.Name, p.ID, p.Status, p.Priority)
	}
	sb.WriteString("\n")

	return nil
}

// writeActiveTasks queries project plans and their milestones to find tasks
// with status "in-progress" and lists them prominently so agents know what
// is currently being worked on.
func (g *SuperContextGenerator) writeActiveTasks(ctx context.Context, sb *strings.Builder, workspaceID string) error {
	if g.store.Projects == nil {
		return nil
	}

	plans, err := g.store.Projects.ListProjectPlans(ctx, workspaceID)
	if err != nil {
		return fmt.Errorf("context.SuperContextGenerator.writeActiveTasks: list plans: %w", err)
	}

	var activeTasks []*taskWithContext
	for _, plan := range plans {
		milestones, err := g.store.Projects.ListMilestones(ctx, plan.ID)
		if err != nil {
			g.logger.Warn("failed to list milestones", "plan", plan.ID, "error", err)
			continue
		}
		for _, ms := range milestones {
			tasks, err := g.store.Projects.ListTasks(ctx, ms.ID)
			if err != nil {
				g.logger.Warn("failed to list tasks", "milestone", ms.ID, "error", err)
				continue
			}
			for _, t := range tasks {
				if t.Status == "in-progress" || t.Status == "in_progress" {
					activeTasks = append(activeTasks, &taskWithContext{
						Task:          t,
						PlanName:      plan.Name,
						MilestoneName: ms.Name,
					})
				}
			}
		}
	}

	if len(activeTasks) == 0 {
		return nil
	}

	sb.WriteString("## Active Tasks\n\n")
	sb.WriteString("Tasks currently in progress:\n\n")
	for _, at := range activeTasks {
		fmt.Fprintf(sb, "- **%s** (`%s`) — %s / %s (priority: %s)\n",
			at.Task.Name, at.Task.ID, at.PlanName, at.MilestoneName, at.Task.Priority)
	}
	sb.WriteString("\n")

	return nil
}

// writeOperationalMandates writes the standard CASAT operational mandates
// that all agents must follow.
func (g *SuperContextGenerator) writeOperationalMandates(sb *strings.Builder) {
	sb.WriteString("## CASAT Operational Mandates\n\n")
	sb.WriteString("All activities — planning, documentation, code discovery, and project management — MUST be performed using CASAT MCP tools.\n")
	sb.WriteString("Before writing any code, use `search_code` and `search_docs` to audit existing logic.\n")
	sb.WriteString("All project plans, milestones, and tasks MUST be managed via the CASAT API (`list_tasks`, `update_task_status`, `add_comment`).\n")
	sb.WriteString("Before submitting code, validate with configured build and test commands via CASAT pipelines.\n\n")
}

// writeToolWorkflow writes the tool-first workflow section with key tool
// invocation patterns for agent reference.
func (g *SuperContextGenerator) writeToolWorkflow(sb *strings.Builder) {
	sb.WriteString("## Tool-First Workflow\n\n")
	sb.WriteString("Use CASAT MCP tools for all workspace operations. Key workflows:\n\n")
	sb.WriteString("- **Coding Standards:** Run `get_standards` or `get_standard_section` for project conventions.\n")
	sb.WriteString("- **Project Structure:** Run `get_project_structure` to explore the directory tree, `list_files_in_dir` to explore a specific sub-directory.\n")
	sb.WriteString("- **Documentation:** Run `search_docs` to find docs by keyword, `list_docs` for all available docs, `get_doc_content` to read one.\n")
	sb.WriteString("- **Code Search:** Run `search_code` for symbols, `get_code_outline` for file structure, `get_dependencies` for import graphs.\n")
	sb.WriteString("- **File Operations:** Use `rm` to delete files, `mv` to move/rename, `mkdir` to create directories, `list_files_in_dir` to browse directory contents.\n")
	sb.WriteString("- **Refactoring:** Use `begin_refactor_transaction` before multi-file changes. Use `extract_code_block`, `insert_code_block`, `move_symbol` for code movement.\n")
	sb.WriteString("- **Build & Validation:** Run `discover_pipelines` to find pipelines, `run_pipeline` to execute.\n")
	sb.WriteString("- **Logs & Debugging:** Run `list_logs` then `get_log_errors` to diagnose issues.\n")
	sb.WriteString("- **Project Management:** Run `list_tasks` for current tasks, `list_projects` for project plans.\n\n")
}

// writeCodingStandards adds a section directing agents to retrieve coding
// standards on demand rather than embedding the full text, which keeps the
// context file concise.
func (g *SuperContextGenerator) writeCodingStandards(sb *strings.Builder, rootPath string) {
	sb.WriteString("## Coding Standards\n\n")

	guidelinesPath := filepath.Join(rootPath, "docs", "CodingGuidelines.md")
	if _, err := os.Stat(guidelinesPath); err == nil {
		sb.WriteString("Run `get_standards` or `get_standard_section` to retrieve project-specific coding conventions on demand.\n\n")
	} else {
		sb.WriteString("No coding standards file found. Create `docs/CodingGuidelines.md` to define project conventions.\n\n")
	}
}

// writeRecentDocs lists markdown files found in the workspace's docs/
// directory so agents are aware of available documentation.
func (g *SuperContextGenerator) writeRecentDocs(sb *strings.Builder, rootPath string) {
	docsDir := filepath.Join(rootPath, "docs")
	entries, err := os.ReadDir(docsDir)
	if err != nil {
		// No docs directory is not an error; just skip the section.
		return
	}

	var docFiles []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(strings.ToLower(e.Name()), ".md") {
			continue
		}
		docFiles = append(docFiles, e.Name())
	}

	if len(docFiles) == 0 {
		return
	}

	sb.WriteString("## Documentation\n\n")
	sb.WriteString("Available documentation in `docs/`:\n\n")
	for _, name := range docFiles {
		fmt.Fprintf(sb, "- `%s`\n", name)
	}
	sb.WriteString("\n")
}

// writePipelines queries the Pipelines repo for definitions in the workspace
// and lists them so agents know what build/test/validation pipelines exist.
func (g *SuperContextGenerator) writePipelines(ctx context.Context, sb *strings.Builder, workspaceID string) error {
	if g.store.Pipelines == nil {
		return nil
	}

	pipelines, err := g.store.Pipelines.ListPipelines(ctx, workspaceID)
	if err != nil {
		return fmt.Errorf("context.SuperContextGenerator.writePipelines: %w", err)
	}

	if len(pipelines) == 0 {
		return nil
	}

	sb.WriteString("## Pipelines\n\n")
	sb.WriteString("Available build and validation pipelines:\n\n")
	for _, p := range pipelines {
		desc := p.Description
		if desc == "" {
			desc = "No description"
		}
		fmt.Fprintf(sb, "- **%s** (`%s`) — %s\n", p.Name, p.ID, desc)
	}
	sb.WriteString("\n")

	return nil
}

// ---------------------------------------------------------------------------
// Internal types
// ---------------------------------------------------------------------------

// taskWithContext pairs a Task with its parent plan and milestone names for
// display purposes.
type taskWithContext struct {
	Task          *repo.Task
	PlanName      string
	MilestoneName string
}

// GeneratedAt returns the current time formatted for inclusion in generated
// files. Exported for use in templates or extended generators.
func GeneratedAt() string {
	return time.Now().UTC().Format(time.RFC3339)
}
