package main

import (
	"bufio"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// wizardConfig collects user answers for bootstrap.yaml generation.
type wizardConfig struct {
	DataDir    string `yaml:"data_dir"`
	ListenAddr string `yaml:"listen_addr"`
	LogLevel   string `yaml:"log_level"`
	Storage    struct {
		Backend string `yaml:"backend"`
	} `yaml:"storage"`
}

// runInitWizard prompts the user for configuration values and writes a
// bootstrap YAML file. Returns the path to the generated file.
func runInitWizard() (string, error) {
	scanner := bufio.NewScanner(os.Stdin)
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolve home directory: %w", err)
	}

	fmt.Println()
	fmt.Println("Hyperax Init Wizard")
	fmt.Println(strings.Repeat("=", 40))
	fmt.Println()

	// 1. Data directory
	defaultDataDir := filepath.Join(homeDir, ".hyperax")
	dataDir := promptWithDefault(scanner, "Data directory", defaultDataDir)
	if err := validatePath(dataDir); err != nil {
		return "", fmt.Errorf("data directory: %w", err)
	}

	// 2. Listen address
	defaultAddr := ":9090"
	listenAddr := promptWithDefault(scanner, "Listen address (host:port)", defaultAddr)
	if err := validateListenAddr(listenAddr); err != nil {
		return "", fmt.Errorf("listen address: %w", err)
	}

	// 3. Storage backend
	fmt.Println()
	fmt.Println("  Available storage backends:")
	fmt.Println("    1) sqlite  (recommended, zero-config)")
	fmt.Println("    2) postgres")
	fmt.Println("    3) mysql")
	fmt.Println()
	backendChoice := promptWithDefault(scanner, "Storage backend [1/2/3]", "1")
	backend := "sqlite"
	switch strings.TrimSpace(backendChoice) {
	case "2", "postgres":
		backend = "postgres"
	case "3", "mysql":
		backend = "mysql"
	}

	// 4. Log level
	fmt.Println()
	fmt.Println("  Log levels: debug, info, warn, error")
	logLevel := promptWithDefault(scanner, "Log level", "info")
	switch strings.ToLower(strings.TrimSpace(logLevel)) {
	case "debug", "info", "warn", "error":
		logLevel = strings.ToLower(strings.TrimSpace(logLevel))
	default:
		fmt.Printf("  Unknown log level %q, defaulting to info\n", logLevel)
		logLevel = "info"
	}

	// Build config struct.
	cfg := wizardConfig{
		DataDir:    dataDir,
		ListenAddr: listenAddr,
		LogLevel:   logLevel,
	}
	cfg.Storage.Backend = backend

	// Create data directory.
	if err := os.MkdirAll(dataDir, 0o755); err != nil {
		return "", fmt.Errorf("create data directory: %w", err)
	}

	// Write hyperax.yaml
	outputPath := filepath.Join(dataDir, "hyperax.yaml")
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return "", fmt.Errorf("marshal config: %w", err)
	}

	header := "# Hyperax bootstrap configuration\n# Generated by 'hyperax init'\n\n"
	if err := os.WriteFile(outputPath, []byte(header+string(data)), 0o644); err != nil {
		return "", fmt.Errorf("write config: %w", err)
	}

	return outputPath, nil
}

// promptWithDefault displays a prompt with a default value and reads user input.
// If the user presses Enter without typing, the default is returned.
func promptWithDefault(scanner *bufio.Scanner, prompt, defaultVal string) string {
	fmt.Printf("  %s [%s]: ", prompt, defaultVal)
	if scanner.Scan() {
		input := strings.TrimSpace(scanner.Text())
		if input != "" {
			return input
		}
	}
	return defaultVal
}

// validatePath checks that a directory path is valid and creatable. It does
// not require the path to exist — only that the parent is accessible and the
// path is absolute or resolvable.
func validatePath(path string) error {
	// Expand ~ prefix.
	if strings.HasPrefix(path, "~/") {
		homeDir, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("cannot expand ~: %w", err)
		}
		path = filepath.Join(homeDir, path[2:])
	}

	abs, err := filepath.Abs(path)
	if err != nil {
		return fmt.Errorf("cannot resolve path: %w", err)
	}

	// Check that the parent directory exists or can be created.
	parent := filepath.Dir(abs)
	if _, err := os.Stat(parent); err != nil {
		return fmt.Errorf("parent directory %s does not exist", parent)
	}

	return nil
}

// validateListenAddr checks that the listen address is a valid host:port.
func validateListenAddr(addr string) error {
	// Allow bare port like ":9090".
	if strings.HasPrefix(addr, ":") {
		addr = "0.0.0.0" + addr
	}

	host, port, err := net.SplitHostPort(addr)
	if err != nil {
		return fmt.Errorf("invalid address %q: must be host:port or :port", addr)
	}

	if port == "" {
		return fmt.Errorf("port is required")
	}

	// Validate host if specified.
	if host != "" && host != "0.0.0.0" && host != "localhost" && host != "127.0.0.1" {
		if ip := net.ParseIP(host); ip == nil {
			// Not an IP — could be a hostname, which is fine.
			_ = host
		}
	}

	return nil
}
